#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@ipsec[-1]
	add ucitrack ipsec
	set ucitrack.@ipsec[-1].init=ipsecvpn
	commit ucitrack
EOF

/etc/init.d/ipsec disable && /etc/init.d/ipsec stop

rm -f /tmp/luci-indexcache
exit 0
